language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t noriom42/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true noriom42/docker-react npm run test -- --coverage